export interface SubCategory {
  id: string;
  label: string;
}

export interface Category {
  id: string;
  label: string;
  icon: string;
  color: string;
  section: 'services' | 'goods';
  subcategories: SubCategory[];
}

export const CATEGORIES: Category[] = [
  // ── SERVICE PROVIDERS ──────────────────────────────────────────────────────
  {
    id: 'house-building',
    label: 'House / Building',
    icon: 'home',
    color: '#1565C0',
    section: 'services',
    subcategories: [
      { id: 'architect',             label: 'Architect' },
      { id: 'civil-engineer',        label: 'Civil Engineer' },
      { id: 'valuer',                label: 'Valuer' },
      { id: 'bore-drilling',         label: 'Bore Drilling / Services' },
      { id: 'pop-expert',            label: 'POP Expert' },
      { id: 'plumber',               label: 'Plumber' },
      { id: 'carpentry',             label: 'Carpentry' },
      { id: 'electrical-installation', label: 'Electrical Installation' },
      { id: 'furniture',             label: 'Furniture' },
      { id: 'mason',                 label: 'Mason' },
      { id: 'water-treatment',       label: 'Water Treatment Installation / Maintenance' },
      { id: 'tiles-marble',          label: 'Tiles / Marble Experts' },
      { id: 'doors-installation',    label: 'Doors Installation' },
      { id: 'window-installation',   label: 'Window Installation' },
      { id: 'mechanic',              label: 'Mechanic' },
      { id: 'air-conditioning',      label: 'Air Condition Installation and Repairs' },
      { id: 'fridge-repairs',        label: 'Fridge Repairs' },
      { id: 'washing-repairs',       label: 'Washing Machine Repairs' },
      { id: 'gas-cooker-repairs',    label: 'Gas Cooker Repairs' },
      { id: 'dstv-installer',        label: 'DSTV Installer' },
      { id: 'television-repairs',    label: 'Television Repairs' },
      { id: 'soakaway-evacuation',   label: 'Soakaway Evacuation' },
      { id: 'fan-repairs',           label: 'Fan Repairs' },
      { id: 'house-painter',         label: 'House Painter' },
      { id: 'street-sweeper',        label: 'Street Sweeper' },
      { id: 'welder-iron-work',      label: 'Welder / Protector / Iron Work' },
      { id: 'cooking-gas-supplier',  label: 'Cooking Gas Supplier' },
    ],
  },
  {
    id: 'generator-repairs',
    label: 'Generator Repairs',
    icon: 'flash',
    color: '#E65100',
    section: 'services',
    subcategories: [
      { id: 'gen-mechanic-plant',    label: 'Generator Mechanic – Plant' },
      { id: 'gen-mechanic-petrol',   label: 'Generator Mechanic – Petrol' },
      { id: 'gen-installation',      label: 'Generator Installation' },
      { id: 'gen-others',            label: 'Others' },
    ],
  },
  {
    id: 'automobile',
    label: 'Automobile Services',
    icon: 'car',
    color: '#37474F',
    section: 'services',
    subcategories: [
      { id: 'welder',                label: 'Welder' },
      { id: 'mechanic-japanese',     label: 'Mechanic – Japanese' },
      { id: 'mechanic-honda',        label: 'Mechanic – Honda' },
      { id: 'mechanic-bus',          label: 'Mechanic – Bus' },
      { id: 'mechanic-truck',        label: 'Mechanic – Truck' },
      { id: 'mechanic-ford',         label: 'Mechanic – Ford' },
      { id: 'panel-beater',          label: 'Panel Beater' },
      { id: 'painter-vehicle',       label: 'Vehicle Painter' },
      { id: 'auto-electrician',      label: 'Auto Electrician – Rewire' },
      { id: 'gear-expert',           label: 'Gear Expert (Select Vehicle & Model)' },
      { id: 'vulcanizer',            label: 'Vulcanizer' },
      { id: 'car-painter',           label: 'Car Painter' },
      { id: 'fokl-lift-service',     label: 'Fokl Lift Operator' },
      { id: 'grain-service',         label: 'Grain Operator' },
      { id: 'mixer-service',         label: 'Mixer Operator' },
      { id: 'cng-installer',         label: 'CNG Installer' },
      { id: 'auto-others',           label: 'Others' },
    ],
  },
  {
    id: 'property-agent',
    label: 'House / Property Agent',
    icon: 'business',
    color: '#6A1B9A',
    section: 'services',
    subcategories: [
      { id: 'long-lease',            label: 'Long Lease' },
      { id: 'short-let',             label: 'Short Let' },
      { id: 'shops',                 label: 'Shops' },
      { id: 'room',                  label: 'Room' },
      { id: 'one-bed',               label: 'One Bedroom' },
      { id: 'two-bed',               label: 'Two Bedroom' },
      { id: 'three-bed',             label: 'Three Bedroom' },
      { id: 'four-bed',              label: 'Four Bedroom & Above' },
      { id: 'duplex',                label: 'Duplex / Above' },
      { id: 'warehouse',             label: 'Warehouse' },
      { id: 'land',                  label: 'Land' },
    ],
  },
  {
    id: 'computer-phone-repairs',
    label: 'Computer / Phone Sales',
    icon: 'phone-portrait',
    color: '#1976D2',
    section: 'services',
    subcategories: [
      { id: 'repair-laptop',         label: 'Laptop' },
      { id: 'repair-tablet',         label: 'Tablet' },
      { id: 'repair-desktop',        label: 'Desktop' },
      { id: 'repair-iphone',         label: 'iPhone' },
      { id: 'repair-android',        label: 'Android' },
      { id: 'repair-other',          label: 'Other' },
    ],
  },
  {
    id: 'event-entertainment',
    label: 'Event / Entertainment',
    icon: 'musical-notes',
    color: '#AD1457',
    section: 'services',
    subcategories: [
      { id: 'mc',                    label: 'MC (Master of Ceremony)' },
      { id: 'comedy',                label: 'Stand Up Comedy' },
      { id: 'chairs-hire',           label: 'Chairs for Hire' },
      { id: 'canopy-hire',           label: 'Canopy for Hire' },
      { id: 'halls',                 label: 'Halls / Event Centre' },
      { id: 'cooking-accessories',   label: 'Cooking Accessories for Hire' },
      { id: 'pots-hire',             label: 'Pots / Plates / Spoons for Hire' },
      { id: 'decoration',            label: 'Decoration' },
      { id: 'ushers',                label: 'Ushers' },
      { id: 'event-planner',         label: 'Event Planner' },
      { id: 'cooling-van',           label: 'Cooling Van' },
      { id: 'live-band',             label: 'Live Band' },
      { id: 'cultural-group',        label: 'Cultural Group' },
      { id: 'souvenirs',             label: 'Souvenirs' },
    ],
  },
  {
    id: 'fashion',
    label: 'Fashion',
    icon: 'shirt',
    color: '#C62828',
    section: 'services',
    subcategories: [
      { id: 'fashion-native-male',   label: 'Fashion Designer – Native Male' },
      { id: 'fashion-native-female', label: 'Fashion Designer – Native Female' },
      { id: 'fashion-senator',       label: 'Fashion Designer – Senator' },
      { id: 'fashion-suites',        label: 'Fashion Designer – Suites' },
      { id: 'fashion-agbada',        label: 'Fashion Designer – Native Agbada' },
      { id: 'shirts',                label: 'Shirt' },
      { id: 'english-wear-ladies',   label: 'English Wear – Ladies' },
      { id: 'wedding-gown',          label: 'Wedding Gown' },
      { id: 'ceremonial-classics',   label: 'Ceremonial / Classics' },
      { id: 't-shirt',               label: 'T-Shirt' },
      { id: 'fashion-other',         label: 'Other' },
    ],
  },
  {
    id: 'saloon-beauty',
    label: 'Saloon & Beauty',
    icon: 'cut',
    color: '#880E4F',
    section: 'services',
    subcategories: [
      { id: 'hair-cut',              label: 'Hair Cut Saloon' },
      { id: 'hair-dressing',         label: 'Hair Dressing Saloon' },
      { id: 'plait-fix',             label: 'Plait & Fix' },
      { id: 'manicure',              label: 'Manicure and Pedicure' },
      { id: 'spas',                  label: 'Spas' },
      { id: 'beauticians',           label: 'Beauticians' },
    ],
  },
  {
    id: 'travels',
    label: 'Travels / Logistics',
    icon: 'airplane',
    color: '#0277BD',
    section: 'services',
    subcategories: [
      { id: 'vehicle-hire',          label: 'Vehicle Hire' },
      { id: 'book-trip',             label: 'Book a Trip' },
      { id: 'inter-city-hire',       label: 'Inter City Car / Bus Hire' },
      { id: 'inter-state-hire',      label: 'Inter State Car / Bus Hire' },
      { id: 'west-coast-hire',       label: 'West Coast Car Hire' },
      { id: 'cycle-delivery',        label: 'Cycle Delivery' },
      { id: 'continental-travel',    label: 'Continental' },
      { id: 'intercontinental-travel', label: 'Intercontinental' },
      { id: 'truck-relocation',      label: 'Truck for Relocation' },
    ],
  },
  {
    id: 'catering',
    label: 'Catering',
    icon: 'restaurant',
    color: '#2E7D32',
    section: 'services',
    subcategories: [
      { id: 'outdoor-catering',      label: 'Outdoor Catering' },
      { id: 'event-coverage',        label: 'Event Coverage' },
      { id: 'catering-services',     label: 'Catering Services' },
    ],
  },
  {
    id: 'industrial',
    label: 'Industrial Repairs',
    icon: 'construct',
    color: '#4527A0',
    section: 'services',
    subcategories: [
      { id: 'cool-room-repairs',     label: 'Cool Room Repairs' },
      { id: 'water-production',      label: 'Water Production Machine' },
      { id: 'pet-blower-repairs',    label: 'Pet Blower Repairs' },
      { id: 'turner',                label: 'Turner' },
      { id: 'pumps',                 label: 'Pumps' },
      { id: 'hvac-repairs',          label: 'HVAC Repairs' },
      { id: 'lift',                  label: 'Lift' },
      { id: 'swimming-pool',         label: 'Swimming Pool' },
      { id: 'industrial-others',     label: 'Others Machineries' },
    ],
  },
  {
    id: 'hiring',
    label: 'Hiring',
    icon: 'cube',
    color: '#00695C',
    section: 'services',
    subcategories: [
      { id: 'hire-fokl-lift',        label: 'Fokl Lift' },
      { id: 'hire-grain',            label: 'Grain' },
      { id: 'hire-mixer',            label: 'Mixer' },
      { id: 'hire-tractor',          label: 'Tractor' },
      { id: 'hire-compressor',       label: 'Compressor' },
      { id: 'hire-self-load',        label: 'Self Load' },
      { id: 'hire-generator',        label: 'Generator' },
      { id: 'hire-extractor',        label: 'Extractor' },
      { id: 'hire-boat',             label: 'Boat' },
      { id: 'hire-barge',            label: 'Barge' },
      { id: 'hire-tugboat',          label: 'Tugboat' },
      { id: 'hire-others',           label: 'Other Machineries' },
    ],
  },
  {
    id: 'financial-services',
    label: 'Audit / Tax / Financial Services',
    icon: 'calculator',
    color: '#1A237E',
    section: 'services',
    subcategories: [
      { id: 'auditor',               label: 'Auditor' },
      { id: 'tax-consultant',        label: 'Tax Consultant' },
      { id: 'trust-adjusters',       label: 'Trust Adjusters' },
      { id: 'insurance',             label: 'Insurance' },
      { id: 'cac-registration',      label: 'CAC Registration' },
      { id: 'financial-others',      label: 'Others' },
    ],
  },
  {
    id: 'logistics',
    label: 'Logistics',
    icon: 'navigate',
    color: '#00695C',
    section: 'services',
    subcategories: [
      { id: 'city-ride',             label: 'City Ride' },
      { id: 'inter-city-logistics',  label: 'Inter City' },
      { id: 'inter-state-logistics', label: 'Inter State' },
      { id: 'continental',           label: 'Continental' },
      { id: 'intercontinental',      label: 'Intercontinental' },
    ],
  },
  {
    id: 'education',
    label: 'Education',
    icon: 'school',
    color: '#1B5E20',
    section: 'services',
    subcategories: [
      { id: 'day-care',              label: 'Day Care' },
      { id: 'primary-nursery',       label: 'Primary / Nursery' },
      { id: 'secondary',             label: 'Secondary' },
      { id: 'adult-education',       label: 'Adult Education Centre' },
      { id: 'home-tutors',           label: 'Home Tutors' },
      { id: 'skill-acquisition',     label: 'Skill Acquisition Centres' },
      { id: 'technical-college',     label: 'Technical College' },
      { id: 'special-kids',          label: 'School for Special Kids' },
      { id: 'gce-jamb',              label: 'GCE / JAMB Tuition' },
    ],
  },

  // ── GOODS AND SERVICES ─────────────────────────────────────────────────────
  {
    id: 'building-material',
    label: 'Building Material',
    icon: 'cube',
    color: '#BF360C',
    section: 'goods',
    subcategories: [
      { id: 'cement',                label: 'Cement' },
      { id: 'chippings',             label: 'Chippings' },
      { id: 'sand',                  label: 'Sand' },
      { id: 'rod',                   label: 'Rod' },
      { id: 'wood',                  label: 'Wood' },
      { id: 'plumbing-material',     label: 'Plumbing Material' },
      { id: 'toiletries-sanitary',   label: 'Toiletries / Sanitary Wares' },
      { id: 'my-bathroom',           label: 'My Bathroom' },
      { id: 'electrical-materials',  label: 'Electrical Materials' },
      { id: 'bore-drilling-material', label: 'Bore Drilling Material' },
      { id: 'pop-material',          label: 'POP Material' },
      { id: 'water-tanks',           label: 'Water Tanks / Treatment' },
      { id: 'tiles-marble-goods',    label: 'Tiles / Marble' },
      { id: 'doors-goods',           label: 'Doors' },
      { id: 'windows-goods',         label: 'Windows' },
      { id: 'kitchen-equipment',     label: 'Kitchen Equipment' },
      { id: 'marbles-goods',         label: 'Marbles' },
      { id: 'epoxy',                 label: 'Epoxy' },
      { id: 'wall-paper',            label: 'Wall Paper' },
      { id: 'luxury-lighting',       label: 'Light / Luxury Lighting' },
      { id: 'interior-decorator',    label: 'Interior Decorator' },
    ],
  },
  {
    id: 'super-store',
    label: 'Super Store',
    icon: 'cart',
    color: '#F57F17',
    section: 'goods',
    subcategories: [
      { id: 'super-store-general',   label: 'Super Store (General)' },
      { id: 'sport-shop',            label: 'Sport Shop' },
      { id: 'gym-equipment',         label: 'Gym Equipment' },
      { id: 'classic-furnitures',    label: 'Classic Furnitures' },
    ],
  },
  {
    id: 'automobile-goods',
    label: 'Automobile',
    icon: 'car-sport',
    color: '#263238',
    section: 'goods',
    subcategories: [
      { id: 'cars-suv',              label: 'Cars / SUV' },
      { id: 'bus-goods',             label: 'Bus' },
      { id: 'truck-goods',           label: 'Truck' },
      { id: 'folk-lift-goods',       label: 'Folk Lift' },
      { id: 'grain-goods',           label: 'Grain' },
      { id: 'tractor-goods',         label: 'Tractor' },
      { id: 'tipper-self-load',      label: 'Tipper / Self-Load' },
      { id: 'auto-goods-others',     label: 'Others' },
    ],
  },
  {
    id: 'spare-parts-tokunbo',
    label: 'Automobile Spare Parts (Tokunbo)',
    icon: 'settings',
    color: '#546E7A',
    section: 'goods',
    subcategories: [
      { id: 'sp-tok-japanese',       label: 'Japanese' },
      { id: 'sp-tok-honda',          label: 'Honda' },
      { id: 'sp-tok-bus',            label: 'Bus' },
      { id: 'sp-tok-truck',          label: 'Truck' },
      { id: 'sp-tok-ford',           label: 'Ford' },
      { id: 'sp-tok-fokl-lift',      label: 'Fokl Lift' },
      { id: 'sp-tok-grain',          label: 'Grain' },
      { id: 'sp-tok-mixer',          label: 'Mixer' },
      { id: 'sp-tok-battery',        label: 'Battery' },
      { id: 'sp-tok-tyre',           label: 'Tyre' },
      { id: 'sp-tok-others',         label: 'Others' },
    ],
  },
  {
    id: 'spare-parts-new',
    label: 'Automobile Spare Parts (Brand New)',
    icon: 'settings-sharp',
    color: '#37474F',
    section: 'goods',
    subcategories: [
      { id: 'sp-new-japanese',       label: 'Japanese' },
      { id: 'sp-new-honda',          label: 'Honda' },
      { id: 'sp-new-bus',            label: 'Bus' },
      { id: 'sp-new-truck',          label: 'Truck' },
      { id: 'sp-new-ford',           label: 'Ford' },
      { id: 'sp-new-fokl-lift',      label: 'Fokl Lift' },
      { id: 'sp-new-grain',          label: 'Grain' },
      { id: 'sp-new-mixer',          label: 'Mixer' },
      { id: 'sp-new-battery',        label: 'Battery' },
      { id: 'sp-new-tyre',           label: 'Tyre' },
      { id: 'sp-new-others',         label: 'Others' },
    ],
  },
  {
    id: 'computers',
    label: 'Computer Sales',
    icon: 'laptop',
    color: '#0D47A1',
    section: 'goods',
    subcategories: [
      { id: 'comp-laptop',           label: 'Laptop' },
      { id: 'comp-desktop',          label: 'Desktop' },
      { id: 'comp-accessories',      label: 'Accessories / Disposables' },
      { id: 'comp-software',         label: 'Software' },
    ],
  },
  {
    id: 'phones',
    label: 'Phone Sales',
    icon: 'phone-portrait',
    color: '#37474F',
    section: 'goods',
    subcategories: [
      { id: 'phone-goods',           label: 'Phone' },
      { id: 'phone-accessories',     label: 'Accessories' },
    ],
  },
  {
    id: 'electronics',
    label: 'Electronics / Instruments',
    icon: 'tv',
    color: '#311B92',
    section: 'goods',
    subcategories: [
      { id: 'tv',                    label: 'TV' },
      { id: 'sound-system',          label: 'Sound System' },
      { id: 'band-instrument',       label: 'Band / Instrument' },
      { id: 'projector',             label: 'Projector' },
      { id: 'camera',                label: 'Camera' },
      { id: 'electronics-others',    label: 'Others' },
    ],
  },
  {
    id: 'furniture-goods',
    label: 'Furniture',
    icon: 'bed',
    color: '#5D4037',
    section: 'goods',
    subcategories: [
      { id: 'luxury-furnitures',     label: 'Luxury Furnitures' },
      { id: 'chairs',                label: 'Chairs' },
      { id: 'table',                 label: 'Table' },
      { id: 'furniture-accessories', label: 'Accessories' },
    ],
  },
  {
    id: 'generator-solar',
    label: 'Generator / Solar',
    icon: 'sunny',
    color: '#F9A825',
    section: 'goods',
    subcategories: [
      { id: 'diesel-generator',      label: 'Diesel Generator / Sound Proof' },
      { id: 'petrol-generator',      label: 'Petrol Generator' },
      { id: 'solar-panel',           label: 'Solar Panel / Light' },
    ],
  },
  {
    id: 'boutique',
    label: 'Boutique',
    icon: 'bag',
    color: '#C62828',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'hotel',
    label: 'Hotel / Bar',
    icon: 'bed',
    color: '#0D47A1',
    section: 'goods',
    subcategories: [
      { id: 'hotel-5star',           label: '5 Star Hotel' },
      { id: 'hotel-4star',           label: '4 Star Hotel' },
      { id: 'hotel-3star',           label: '3 Star Hotel' },
      { id: 'hotel-1star',           label: '1 Star Hotel' },
      { id: 'motel',                 label: 'Motel' },
      { id: 'restaurant-bar',        label: 'Restaurant / Bar' },
      { id: 'night-club',            label: 'Night Club' },
    ],
  },
  {
    id: 'real-estate',
    label: 'Real Estate',
    icon: 'map',
    color: '#1A237E',
    section: 'goods',
    subcategories: [
      { id: 'real-estate-land',      label: 'Land' },
      { id: 'real-estate-property',  label: 'House / Property' },
    ],
  },
  {
    id: 'hospital',
    label: 'Hospital',
    icon: 'medkit',
    color: '#B71C1C',
    section: 'goods',
    subcategories: [
      { id: 'general-medicine',      label: 'General Medicine' },
      { id: 'optician',              label: 'Optician' },
      { id: 'dental',                label: 'Dental' },
      { id: 'gynecology',            label: 'Gynecology' },
      { id: 'orthopedic',            label: 'Orthopedic' },
      { id: 'hospital-others',       label: 'Others' },
    ],
  },
  {
    id: 'laboratory',
    label: 'Laboratory',
    icon: 'flask',
    color: '#1B5E20',
    section: 'goods',
    subcategories: [
      { id: 'lab-equipment',         label: 'Lab Equipment / Machines' },
      { id: 'lab-accessories',       label: 'Accessories / Disposables' },
    ],
  },
  {
    id: 'marine',
    label: 'Marine',
    icon: 'boat',
    color: '#006064',
    section: 'goods',
    subcategories: [
      { id: 'sea-craft',             label: 'Sea Craft' },
      { id: 'boat',                  label: 'Boat' },
      { id: 'outboard-engine-boat',  label: 'Outboard Engine Boat' },
      { id: 'canoe',                 label: 'Canoe' },
    ],
  },
  {
    id: 'oil-gas',
    label: 'Oil / Gas',
    icon: 'flame',
    color: '#BF360C',
    section: 'goods',
    subcategories: [
      { id: 'gas-station-equipment', label: 'Gas Station Equipment' },
      { id: 'gas-bottle-accessory',  label: 'Gas Bottle / Accessory' },
      { id: 'drilling-equipment',    label: 'Drilling Equipment' },
    ],
  },
  {
    id: 'finance',
    label: 'Finance',
    icon: 'cash',
    color: '#1A237E',
    section: 'goods',
    subcategories: [
      { id: 'micro-finance',         label: 'Micro Finance' },
      { id: 'bank',                  label: 'Bank' },
      { id: 'cooperative-society',   label: 'Cooperative Society' },
    ],
  },
  {
    id: 'job-vacancy',
    label: 'Job Vacancy',
    icon: 'briefcase',
    color: '#1565C0',
    section: 'goods',
    subcategories: [
      { id: 'labour-contractors',    label: 'Labour Contractors' },
      { id: 'recruiters',            label: 'Recruiters' },
    ],
  },
  {
    id: 'skilled-artisan',
    label: 'Skilled / Artisan / Services',
    icon: 'hammer',
    color: '#4E342E',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'village-mat',
    label: 'Village Mat',
    icon: 'leaf',
    color: '#33691E',
    section: 'goods',
    subcategories: [],
  },
];

export const SERVICE_CATEGORIES = CATEGORIES.filter(c => c.section === 'services');
export const GOODS_CATEGORIES   = CATEGORIES.filter(c => c.section === 'goods');

export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find(c => c.id === id);
}

export const QUICK_CATEGORIES = [
  'house-building',
  'automobile',
  'property-agent',
  'event-entertainment',
  'education',
  'hospital',
  'hotel',
  'travels',
  'catering',
  'super-store',
  'job-vacancy',
  'logistics',
  'industrial',
  'financial-services',
  'marine',
  'oil-gas',
];
