export interface SubCategory {
  id: string;
  label: string;
}

export interface Category {
  id: string;
  label: string;
  icon: string;
  color: string;
  section: 'services' | 'goods';
  subcategories: SubCategory[];
}

export const CATEGORIES: Category[] = [
  // ── SERVICE PROVIDERS ──────────────────────────────────────────────────
  {
    id: 'house-building',
    label: 'House / Building',
    icon: 'home',
    color: '#1565C0',
    section: 'services',
    subcategories: [
      { id: 'architect', label: 'Architect' },
      { id: 'civil-engineer', label: 'Civil Engineer' },
      { id: 'valuer', label: 'Valuer' },
      { id: 'bore-drilling', label: 'Bore Drilling / Services' },
      { id: 'pop-expert', label: 'POP Expert' },
      { id: 'plumber', label: 'Plumber' },
      { id: 'carpentry', label: 'Carpentry' },
      { id: 'electrical-installation', label: 'Electrical Installation' },
      { id: 'furniture', label: 'Furniture' },
      { id: 'mason', label: 'Mason' },
      { id: 'water-treatment', label: 'Water Treatment Installation / Maintenance' },
      { id: 'tiles-marble', label: 'Tiles / Marble Experts' },
      { id: 'doors-installation', label: 'Doors Installation' },
      { id: 'window-installation', label: 'Window Installation' },
      { id: 'mechanic', label: 'Mechanic' },
      { id: 'air-conditioning', label: 'Air Condition Installation and Repairs' },
      { id: 'fridge-repairs', label: 'Fridge Repairs' },
      { id: 'washing-repairs', label: 'Washing Machine Repairs' },
      { id: 'gas-cooker-repairs', label: 'Gas Cooker Repairs' },
      { id: 'dstv-installer', label: 'DSTV Installer' },
      { id: 'television-repairs', label: 'Television Repairs' },
      { id: 'soakaway-evacuation', label: 'Soakaway Evacuation' },
      { id: 'fan-repairs', label: 'Fan Repairs' },
      { id: 'house-painter', label: 'House Painter' },
      { id: 'street-sweeper', label: 'Street Sweeper' },
    ],
  },
  {
    id: 'generator-repairs',
    label: 'Generator Repairs',
    icon: 'flash',
    color: '#E65100',
    section: 'services',
    subcategories: [
      { id: 'gen-mechanic-plant', label: 'Generator Mechanic – Plant' },
      { id: 'gen-mechanic-petrol', label: 'Generator Mechanic – Petrol' },
      { id: 'gen-installation', label: 'Generator Installation' },
    ],
  },
  {
    id: 'automobile',
    label: 'Automobile Services',
    icon: 'car',
    color: '#37474F',
    section: 'services',
    subcategories: [
      { id: 'welder', label: 'Welder' },
      { id: 'mechanic-japanese', label: 'Mechanic – Japanese' },
      { id: 'mechanic-honda', label: 'Mechanic – Honda' },
      { id: 'mechanic-bus', label: 'Mechanic – Bus' },
      { id: 'mechanic-truck', label: 'Mechanic – Truck' },
      { id: 'panel-beater', label: 'Panel Beater' },
      { id: 'painter-vehicle', label: 'Vehicle Painter' },
      { id: 'auto-electrician', label: 'Auto Electrician – Rewire' },
      { id: 'gear-expert', label: 'Gear Expert (Select Vehicle & Model)' },
      { id: 'vulcanizer', label: 'Vulcanizer' },
      { id: 'car-painter', label: 'Car Painter' },
    ],
  },
  {
    id: 'automobile-spare-parts',
    label: 'Automobile Spare Parts',
    icon: 'settings',
    color: '#546E7A',
    section: 'services',
    subcategories: [
      { id: 'tyre-new', label: 'Tyre – Brand New' },
      { id: 'tyre-tokunbo', label: 'Tyre – Tokunbo' },
      { id: 'battery', label: 'Battery' },
      { id: 'japanese-spare', label: 'Japanese Spare Parts (Select Make)' },
      { id: 'honda-spare', label: 'Honda Spare Parts' },
      { id: 'ford-spare', label: 'Ford Spare Parts' },
      { id: 'truck-repairs', label: 'Truck Repairs' },
      { id: 'etc-spare', label: 'Other Spare Parts' },
    ],
  },
  {
    id: 'property-agent',
    label: 'House / Property Agent',
    icon: 'business',
    color: '#6A1B9A',
    section: 'services',
    subcategories: [
      { id: 'long-lease', label: 'Long Lease' },
      { id: 'shops', label: 'Shops' },
      { id: 'room', label: 'Room' },
      { id: 'one-bed', label: 'One Bedroom' },
      { id: 'two-bed', label: 'Two Bedroom' },
      { id: 'three-bed', label: 'Three Bedroom' },
      { id: 'four-bed', label: 'Four Bedroom & Above' },
      { id: 'duplex', label: 'Duplex / Above' },
      { id: 'warehouse', label: 'Warehouse' },
      { id: 'land', label: 'Land' },
    ],
  },
  {
    id: 'event-entertainment',
    label: 'Event / Entertainment',
    icon: 'musical-notes',
    color: '#AD1457',
    section: 'services',
    subcategories: [
      { id: 'mc', label: 'MC (Master of Ceremony)' },
      { id: 'comedy', label: 'Stand Up Comedy' },
      { id: 'chairs-hire', label: 'Chairs for Hire' },
      { id: 'canopy-hire', label: 'Canopy for Hire' },
      { id: 'halls', label: 'Halls / Event Centre' },
      { id: 'cooking-accessories', label: 'Cooking Accessories for Hire' },
      { id: 'pots-hire', label: 'Pots / Plates / Spoons for Hire' },
    ],
  },
  {
    id: 'fashion',
    label: 'Fashion',
    icon: 'shirt',
    color: '#C62828',
    section: 'services',
    subcategories: [
      { id: 'fashion-native-male', label: 'Fashion Designer – Native Male' },
      { id: 'fashion-native-female', label: 'Fashion Designer – Native Female' },
      { id: 'fashion-senator', label: 'Fashion Designer – Senator' },
      { id: 'fashion-suites', label: 'Fashion Designer – Suites' },
      { id: 'fashion-agbada', label: 'Fashion Designer – Native Agbada' },
      { id: 'shirts', label: 'Shirt' },
      { id: 'english-wear-ladies', label: 'English Wear – Ladies' },
    ],
  },
  {
    id: 'saloon-beauty',
    label: 'Saloon & Beauty',
    icon: 'cut',
    color: '#880E4F',
    section: 'services',
    subcategories: [
      { id: 'hair-cut', label: 'Hair Cut Saloon' },
      { id: 'hair-dressing', label: 'Hair Dressing Saloon' },
      { id: 'plait-fix', label: 'Plait & Fix' },
      { id: 'manicure', label: 'Manicure and Pedicure' },
      { id: 'spas', label: 'Spas' },
    ],
  },
  {
    id: 'travels',
    label: 'Travels',
    icon: 'airplane',
    color: '#0277BD',
    section: 'services',
    subcategories: [
      { id: 'vehicle-hire', label: 'Vehicle Hire' },
      { id: 'book-trip', label: 'Book a Trip' },
      { id: 'inter-city-hire', label: 'Inter City Car / Bus Hire' },
      { id: 'inter-state-hire', label: 'Inter State Car / Bus Hire' },
      { id: 'west-coast-hire', label: 'West Coast Car Hire' },
    ],
  },
  {
    id: 'catering',
    label: 'Catering',
    icon: 'restaurant',
    color: '#2E7D32',
    section: 'services',
    subcategories: [
      { id: 'outdoor-catering', label: 'Outdoor Catering' },
      { id: 'event-coverage', label: 'Event Coverage' },
      { id: 'catering-services', label: 'Catering Services' },
    ],
  },
  {
    id: 'industrial',
    label: 'Industrial',
    icon: 'construct',
    color: '#4527A0',
    section: 'services',
    subcategories: [
      { id: 'cool-room-repairs', label: 'Cool Room Repairs' },
      { id: 'water-production', label: 'Water Production Machine' },
      { id: 'pet-blower-repairs', label: 'Pet Blower Repairs' },
      { id: 'turner', label: 'Turner' },
    ],
  },
  {
    id: 'logistics',
    label: 'Logistics',
    icon: 'navigate',
    color: '#00695C',
    section: 'services',
    subcategories: [
      { id: 'city-ride', label: 'City Ride' },
      { id: 'inter-city-logistics', label: 'Inter City' },
      { id: 'inter-state-logistics', label: 'Inter State' },
      { id: 'continental', label: 'Continental' },
      { id: 'intercontinental', label: 'Intercontinental' },
    ],
  },
  {
    id: 'education',
    label: 'Education',
    icon: 'school',
    color: '#1B5E20',
    section: 'services',
    subcategories: [
      { id: 'day-care', label: 'Day Care' },
      { id: 'primary-nursery', label: 'Primary / Nursery' },
      { id: 'secondary', label: 'Secondary' },
      { id: 'adult-education', label: 'Adult Education Centre' },
      { id: 'home-tutors', label: 'Home Tutors' },
      { id: 'skill-acquisition', label: 'Skill Acquisition Centres' },
      { id: 'technical-college', label: 'Technical College' },
      { id: 'special-kids', label: 'School for Special Kids' },
    ],
  },

  // ── GOODS AND SERVICES ─────────────────────────────────────────────────
  {
    id: 'super-store',
    label: 'Super Store',
    icon: 'cart',
    color: '#F57F17',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'boutique',
    label: 'Boutique',
    icon: 'bag',
    color: '#C62828',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'hotel',
    label: 'Hotel',
    icon: 'bed',
    color: '#0D47A1',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'restaurant-bar',
    label: 'Restaurant & Bar',
    icon: 'beer',
    color: '#BF360C',
    section: 'goods',
    subcategories: [
      { id: 'eatery', label: 'Eatery' },
      { id: 'native-restaurant', label: 'Native Restaurant' },
    ],
  },
  {
    id: 'real-estate',
    label: 'Real Estate',
    icon: 'map',
    color: '#1A237E',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'rental',
    label: 'Rental',
    icon: 'key',
    color: '#4A148C',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'building-material',
    label: 'Building Material',
    icon: 'cube',
    color: '#BF360C',
    section: 'goods',
    subcategories: [
      { id: 'cement', label: 'Cement' },
      { id: 'chippings', label: 'Chippings' },
      { id: 'sand', label: 'Sand' },
      { id: 'rod', label: 'Rod' },
      { id: 'wood', label: 'Wood' },
      { id: 'plumbing-material', label: 'Plumbing Material' },
      { id: 'toiletries-sanitary', label: 'Toiletries / Sanitary Wares' },
      { id: 'my-bathroom', label: 'My Bathroom' },
      { id: 'electrical-materials', label: 'Electrical Materials' },
      { id: 'bore-drilling-material', label: 'Bore Drilling Material' },
      { id: 'pop-material', label: 'POP Material' },
      { id: 'water-tanks', label: 'Water Tanks / Treatment' },
      { id: 'tiles-marble-goods', label: 'Tiles / Marble' },
      { id: 'doors-goods', label: 'Doors' },
      { id: 'windows-goods', label: 'Windows' },
    ],
  },
  {
    id: 'hospital',
    label: 'Hospital',
    icon: 'medkit',
    color: '#B71C1C',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'laboratory',
    label: 'Laboratory',
    icon: 'flask',
    color: '#1B5E20',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'automobile-goods',
    label: 'Automobile',
    icon: 'car-sport',
    color: '#263238',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'sea-craft',
    label: 'Sea Craft',
    icon: 'boat',
    color: '#006064',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'job-vacancy',
    label: 'Job Vacancy',
    icon: 'briefcase',
    color: '#1565C0',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'skilled-artisan',
    label: 'Skilled / Artisan / Services',
    icon: 'hammer',
    color: '#4E342E',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'village-mat',
    label: 'Village Mat',
    icon: 'leaf',
    color: '#33691E',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'finance',
    label: 'Finance',
    icon: 'cash',
    color: '#1A237E',
    section: 'goods',
    subcategories: [],
  },
  {
    id: 'phones',
    label: 'Phones',
    icon: 'phone-portrait',
    color: '#37474F',
    section: 'goods',
    subcategories: [
      { id: 'phone-repairs', label: 'Phone Repairs' },
    ],
  },
  {
    id: 'computers',
    label: 'Computer',
    icon: 'laptop',
    color: '#0D47A1',
    section: 'goods',
    subcategories: [
      { id: 'computer-repairs', label: 'Computer Repairs' },
    ],
  },
  {
    id: 'furniture-goods',
    label: 'Furniture',
    icon: 'bed',
    color: '#5D4037',
    section: 'goods',
    subcategories: [
      { id: 'chairs', label: 'Chairs' },
      { id: 'table', label: 'Table' },
      { id: 'accessories', label: 'Accessories' },
    ],
  },
];

export const SERVICE_CATEGORIES = CATEGORIES.filter(c => c.section === 'services');
export const GOODS_CATEGORIES = CATEGORIES.filter(c => c.section === 'goods');

export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find(c => c.id === id);
}

export const QUICK_CATEGORIES = [
  'house-building',
  'automobile',
  'property-agent',
  'event-entertainment',
  'education',
  'hospital',
  'restaurant-bar',
  'travels',
  'catering',
  'super-store',
  'job-vacancy',
  'logistics',
];
